import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Boombang Alpha 0.1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <link rel="icon" href="https://pbs.twimg.com/media/ExjwN2RXEAQO5pn.png" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
